modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraft_rpgweapons"
version="1.1.2"
displayName="minecraft RPGWeapons"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MaxDogGamer"

[[dependencies.minecraft_rpgweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




